### PR TITLE
fpga_plugin: support in-tree kernel driver

### PR DESCRIPTION
**Pull request by bart0sh**
Extended fpga plugin to support both in-tree(DFL) and
out-of-tree (OPAE) kernel drivers.

### CODE REVIEW

**Comment by bart0sh** [comment]
@rojkov, @kad please review

**Comment by rojkov** [comment]
The current FPGA plugin implements two interfaces `Scanner` and `PostAllocator`. This PR introduces a new scanner for DFL, so that we have two different scanners now: one for DFL and another for OPAE. I would rather create two `struct`s implementing `Scanner` and make `devicePlugin` an adapter for these two scanners:
```
type fpgaScanner interface {
    scanFPGAs() (dpapi.DeviceTree, error)
}

type devicePlugin struct {
   ...
   fpgaScanner scanner
}

func (dp *devicePlugin) Scan(notifier dpapi.Notifier) error {
	for {
		devTree, err := dp.scanner.scanFPGAs()
		if err != nil {
			return err
		}

		notifier.Notify(devTree)

		time.Sleep(5 * time.Second)
	}
}


func newFpgaScanner() (fpgaScanner, error) {
    // create a scanner depending on driver's availability
    ...
}
```

**Comment by bart0sh** [comment]
@rojkov Updated the PR, please review again. 

I tried to follow your suggestion, but it didn't work for me. So I come up with another one, which is better utilizing existing code and doesn't use nested structures.

**Comment by rojkov** [comment]
Looks good now.

**Comment by bart0sh** [comment]
@kad please review & merge if you don't mind.

**Comment by bart0sh** [comment]
@kad replaced directory reading with filepath.Glob as you've suggested.

**Pull request merged**
